<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>auv_decision_ros</name>
  <version>0.1.0</version>
  <description>ROS2 wrapper for AUV behavior tree decision core.</description>
  <maintainer email="zmem063@todo.todo">zmem063</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>py_trees</depend>
  <depend>auv_interfaces</depend>
  <depend>auv_decision_core</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
