# Makefile generated by the project manager
#


# GENERATED: Wed Aug 17 13:57:53 +0800 2022
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = vx6.8_lastest.wpj
PRJ_FULL_PATH  = C:/WindRiver/workspace/csd_vx6.8_lastest
PRJ_TYPE       = vxWorks
PRJ_OBJS       = sysALib.o sysLib.o usrAppInit.o usrRtpAppInit.o prjConfig.o linkSyms.o CtrlAlgorithm.o DataProcess.o PowerManage.o SailingBox.o sax.o xmlparse.o xmlrole.o xmltok.o xmltok_impl.o xmltok_ns.o xpp.o xppTutorialAll.o XMLFile.o com.o dtp.o main.o canTest.o SecurityEmergencyManage.o
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      = romInit.o romStart.o $(BOOT_EXTRA)
BUILD_SPEC     = default
BSP_DIR        = $(TGT_DIR)/config/BSP
VSB_DIR        = $(TGT_DIR)/lib
TGT_DIR        = $(WIND_BASE)/target



## set searching directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.s $(BSP_DIR)


## build-configuration info

ifeq ($(BUILD_SPEC),default)
CPU            = PENTIUM
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks
endif

ifeq ($(BUILD_SPEC),default_rom)
CPU            = PENTIUM
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_rom
endif

ifeq ($(BUILD_SPEC),default_romCompress)
CPU            = PENTIUM
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_romCompress
endif

ifeq ($(BUILD_SPEC),default_romResident)
CPU            = PENTIUM
TOOL           = gnu
TOOL_FAMILY    = gnu
DEFAULT_RULE   = vxWorks_romResident
endif


## Memory adresses variables

RAM_LOW_ADRS = 00308000
RAM_HIGH_ADRS = 00108000
LOCAL_MEM_LOCAL_ADRS = (0x00100000)

## component-configuration info

COMPONENTS = DRV_KBD_I8042 \
	DRV_NVRAM_FILE \
	DRV_SIO_NS16550 \
	DRV_TIMER_I8253 \
	DRV_VGA_M6845 \
	INCLUDE_ADR_SPACE_LIB \
	INCLUDE_ADR_SPACE_SHELL_CMD \
	INCLUDE_ADR_SPACE_SHOW \
	INCLUDE_ANSI_ABORT \
	INCLUDE_ANSI_ABS \
	INCLUDE_ANSI_ASSERT \
	INCLUDE_ANSI_ATOF \
	INCLUDE_ANSI_BSEARCH \
	INCLUDE_ANSI_CTYPE \
	INCLUDE_ANSI_LOCALE \
	INCLUDE_ANSI_LONGJMP \
	INCLUDE_ANSI_MATH \
	INCLUDE_ANSI_MEMCHR \
	INCLUDE_ANSI_MEMCMP \
	INCLUDE_ANSI_MEMCPY \
	INCLUDE_ANSI_MEMMOVE \
	INCLUDE_ANSI_MEMSET \
	INCLUDE_ANSI_STDIO \
	INCLUDE_ANSI_STDIO_EXTRA \
	INCLUDE_ANSI_STDLIB \
	INCLUDE_ANSI_STDLIB_NUMBERS \
	INCLUDE_ANSI_STRCASECMP \
	INCLUDE_ANSI_STRCAT \
	INCLUDE_ANSI_STRCMP \
	INCLUDE_ANSI_STRCPY \
	INCLUDE_ANSI_STRDUP \
	INCLUDE_ANSI_STRERROR \
	INCLUDE_ANSI_STRING \
	INCLUDE_ANSI_STRLCPY \
	INCLUDE_ANSI_STRLEN \
	INCLUDE_ANSI_STRNCASECMP \
	INCLUDE_ANSI_STRNCAT \
	INCLUDE_ANSI_STRNCMP \
	INCLUDE_ANSI_STRNCPY \
	INCLUDE_ANSI_STRTOD \
	INCLUDE_ANSI_TIME \
	INCLUDE_APPL_LOG_UTIL \
	INCLUDE_ATA \
	INCLUDE_ATOMIC_OPERATORS \
	INCLUDE_AVL_UINT_TREES \
	INCLUDE_BASE_KERNEL \
	INCLUDE_BLIB \
	INCLUDE_BMPLIB \
	INCLUDE_BOOT_LINE_INIT \
	INCLUDE_BSP_MACROS \
	INCLUDE_CACHE_ENABLE \
	INCLUDE_CACHE_SUPPORT \
	INCLUDE_CHECKSUM \
	INCLUDE_CLASS_LIB \
	INCLUDE_CLASS_LIST \
	INCLUDE_COMMON_NET \
	INCLUDE_COPROCESSOR \
	INCLUDE_COPROCESSOR_SHOW \
	INCLUDE_CPLUS_DEMANGLER \
	INCLUDE_CPU_LIGHT_PWR_MGR \
	INCLUDE_CPU_PWR_MGMT \
	INCLUDE_CTORS_DTORS \
	INCLUDE_DEBUG \
	INCLUDE_DEBUG_SHELL_CMD \
	INCLUDE_DEVICE_MANAGER \
	INCLUDE_DISK_UTIL \
	INCLUDE_DISK_UTIL_SHELL_CMD \
	INCLUDE_DLL \
	INCLUDE_DMA_SYS \
	INCLUDE_DOSFS \
	INCLUDE_DOSFS_CHKDSK \
	INCLUDE_DOSFS_DIR_FIXED \
	INCLUDE_DOSFS_DIR_VFAT \
	INCLUDE_DOSFS_FAT \
	INCLUDE_DOSFS_FMT \
	INCLUDE_DOSFS_MAIN \
	INCLUDE_DOSFS_SHOW \
	INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE \
	INCLUDE_EDR_ERRLOG \
	INCLUDE_EDR_PM \
	INCLUDE_EDR_SHELL_CMD \
	INCLUDE_EDR_SHOW \
	INCLUDE_EDR_STUB \
	INCLUDE_EDR_SYSDBG_FLAG \
	INCLUDE_END \
	INCLUDE_END_COMMON \
	INCLUDE_END_ETHER_HDR \
	INCLUDE_ENV_VARS \
	INCLUDE_ERF \
	INCLUDE_ETHERNET \
	INCLUDE_EVENTPOINT_STUB \
	INCLUDE_EXC_HANDLING \
	INCLUDE_EXC_SHOW \
	INCLUDE_EXC_TASK \
	INCLUDE_FEI8255X_VXB_END \
	INCLUDE_FLOATING_POINT \
	INCLUDE_FORMATTED_IO \
	INCLUDE_FORMATTED_OUT_BASIC \
	INCLUDE_FP_TYPE \
	INCLUDE_FS_EVENT_UTIL \
	INCLUDE_FS_MONITOR \
	INCLUDE_FTP \
	INCLUDE_GENERICPHY \
	INCLUDE_GETADDRINFO_SYSCTL \
	INCLUDE_GETOPT \
	INCLUDE_GNU_INTRINSICS \
	INCLUDE_HANDLE_SHOW \
	INCLUDE_HASH \
	INCLUDE_HISTORY_FILE_SHELL_CMD \
	INCLUDE_HOOKS \
	INCLUDE_HOOK_SHOW \
	INCLUDE_HOST_TBL \
	INCLUDE_HOST_TBL_SYSCTL \
	INCLUDE_HWMEM_ALLOC \
	INCLUDE_HW_FP \
	INCLUDE_IFCONFIG \
	INCLUDE_IO_BASIC \
	INCLUDE_IO_FILE_SYSTEM \
	INCLUDE_IO_MISC \
	INCLUDE_IO_POSIX \
	INCLUDE_IO_REMOVABLE \
	INCLUDE_IO_RTP \
	INCLUDE_IO_SYSTEM \
	INCLUDE_IPAIP \
	INCLUDE_IPAIP_GLOBAL_CONFIGS \
	INCLUDE_IPCOM \
	INCLUDE_IPCOM_SHELL_CMD \
	INCLUDE_IPCOM_USE_AUTH \
	INCLUDE_IPCOM_USE_ETHERNET \
	INCLUDE_IPCOM_USE_INET \
	INCLUDE_IPFTPS \
	INCLUDE_IPIFCONFIG_CMD \
	INCLUDE_IPNET \
	INCLUDE_IPNET_IFCONFIG_1 \
	INCLUDE_IPNET_LOOPBACK_CONFIG \
	INCLUDE_IPNET_SOCKET \
	INCLUDE_IPNET_STACK \
	INCLUDE_IPNET_SYSCTL \
	INCLUDE_IPNET_USE_LOOPBACK \
	INCLUDE_IPNET_USE_ROUTESOCK \
	INCLUDE_IPNET_USE_SOCK_COMPAT \
	INCLUDE_IPPING_CMD \
	INCLUDE_IPPROXYARP \
	INCLUDE_IPSYSCTL_CMD \
	INCLUDE_IPTCP \
	INCLUDE_IPTELNETS \
	INCLUDE_IPV4 \
	INCLUDE_IPWRAP_GETADDRINFO \
	INCLUDE_IPWRAP_IFCONFIG \
	INCLUDE_IPWRAP_INETLIB \
	INCLUDE_IPWRAP_PING \
	INCLUDE_ISR_DEFER \
	INCLUDE_JOB_QUEUE \
	INCLUDE_JOB_TASK \
	INCLUDE_KERNEL \
	INCLUDE_KERNEL_ARCH \
	INCLUDE_LINKBUFPOOL \
	INCLUDE_LOADER \
	INCLUDE_LOADER_CODE \
	INCLUDE_LOGGING \
	INCLUDE_LSTLIB \
	INCLUDE_MAPPED_FILES_SHOW \
	INCLUDE_MAPPED_FILES_SHOW_SHELL_CMD \
	INCLUDE_MBUF_UTIL1 \
	INCLUDE_MBUF_UTIL2 \
	INCLUDE_MEMORY_CONFIG \
	INCLUDE_MEM_EDR \
	INCLUDE_MEM_EDR2 \
	INCLUDE_MEM_EDR_RTP_SHELL_CMD \
	INCLUDE_MEM_EDR_RTP_SHOW \
	INCLUDE_MEM_EDR_SHELL_CMD \
	INCLUDE_MEM_EDR_SHOW \
	INCLUDE_MEM_MGR_BASIC \
	INCLUDE_MEM_MGR_FULL \
	INCLUDE_MEM_MGR_INFO \
	INCLUDE_MEM_RTP \
	INCLUDE_MEM_SHOW \
	INCLUDE_MII_BUS \
	INCLUDE_MMU_BASIC \
	INCLUDE_MMU_GLOBAL_MAP \
	INCLUDE_MODULE_MANAGER \
	INCLUDE_MODULE_SHELL_CMD \
	INCLUDE_MSG_Q \
	INCLUDE_MSG_Q_CREATE_DELETE \
	INCLUDE_MSG_Q_EVENTS \
	INCLUDE_MSG_Q_INFO \
	INCLUDE_MSG_Q_OPEN \
	INCLUDE_MUX \
	INCLUDE_MUX2 \
	INCLUDE_MUX2_OVER_END \
	INCLUDE_MUXTK \
	INCLUDE_MUXTK_OVER_END \
	INCLUDE_MUX_COMMON \
	INCLUDE_NBIO_LOG \
	INCLUDE_NETBUFLIB \
	INCLUDE_NETBUFPOOL \
	INCLUDE_NETMASK_GET \
	INCLUDE_NETWORK \
	INCLUDE_NET_BOOT \
	INCLUDE_NET_DAEMON \
	INCLUDE_NET_DRV \
	INCLUDE_NET_HOST_SETUP \
	INCLUDE_NET_REM_IO \
	INCLUDE_NET_SYSCTL \
	INCLUDE_NON_VOLATILE_RAM \
	INCLUDE_OBJ_INFO \
	INCLUDE_OBJ_LIB \
	INCLUDE_OBJ_OPEN \
	INCLUDE_OBJ_OWNERSHIP \
	INCLUDE_OFFSET_SYMBOLS \
	INCLUDE_PARAM_SYS \
	INCLUDE_PCI_BUS \
	INCLUDE_PCI_OLD_CONFIG_ROUTINES \
	INCLUDE_PC_CONSOLE \
	INCLUDE_PENTIUM_PCI \
	INCLUDE_PG_MGR_LIB \
	INCLUDE_PG_MGR_SHOW \
	INCLUDE_PG_POOL_LIB \
	INCLUDE_PG_POOL_PHYS_LIB \
	INCLUDE_PG_POOL_SHOW \
	INCLUDE_PG_POOL_VIRT_LIB \
	INCLUDE_PIIX4_ATADMA \
	INCLUDE_PING \
	INCLUDE_PIPES \
	INCLUDE_PLB_BUS \
	INCLUDE_POOL \
	INCLUDE_POSIX_CLOCKS \
	INCLUDE_POSIX_DIRLIB \
	INCLUDE_POSIX_FS \
	INCLUDE_POSIX_MAPPED_FILES \
	INCLUDE_PTYDRV \
	INCLUDE_Q_FIFO \
	INCLUDE_Q_LIB \
	INCLUDE_Q_PRI_BMAP \
	INCLUDE_Q_PRI_DELTA \
	INCLUDE_Q_PRI_LIST \
	INCLUDE_RAWFS \
	INCLUDE_REBOOT_HOOKS \
	INCLUDE_REMLIB \
	INCLUDE_REMLIB_SYSCTL \
	INCLUDE_RNG_BUF \
	INCLUDE_RTP \
	INCLUDE_RTP_ARCH \
	INCLUDE_RTP_DEBUG \
	INCLUDE_RTP_DEBUG_COMMAND \
	INCLUDE_RTP_HOOKS \
	INCLUDE_RTP_SHELL_C \
	INCLUDE_RTP_SHELL_CMD \
	INCLUDE_RTP_SHOW \
	INCLUDE_RTP_SHOW_SHELL_CMD \
	INCLUDE_SC_IOS \
	INCLUDE_SC_KERNEL \
	INCLUDE_SC_MMAN \
	INCLUDE_SC_POSIX \
	INCLUDE_SC_SD \
	INCLUDE_SC_SHL \
	INCLUDE_SC_SOCKLIB \
	INCLUDE_SC_SYSCTL \
	INCLUDE_SECURITY \
	INCLUDE_SELECT \
	INCLUDE_SELECT_SUPPORT \
	INCLUDE_SEM_BINARY \
	INCLUDE_SEM_BINARY_CREATE \
	INCLUDE_SEM_COUNTING \
	INCLUDE_SEM_COUNTING_CREATE \
	INCLUDE_SEM_DELETE \
	INCLUDE_SEM_EVENTS \
	INCLUDE_SEM_EXCHANGE \
	INCLUDE_SEM_INFO \
	INCLUDE_SEM_LIB \
	INCLUDE_SEM_MUTEX \
	INCLUDE_SEM_MUTEX_CREATE \
	INCLUDE_SEM_OPEN \
	INCLUDE_SEM_READ_WRITE \
	INCLUDE_SEM_READ_WRITE_CREATE \
	INCLUDE_SHARED_DATA \
	INCLUDE_SHARED_DATA_SHOW \
	INCLUDE_SHARED_DATA_SHOW_SHELL_CMD \
	INCLUDE_SHELL \
	INCLUDE_SHELL_CORE \
	INCLUDE_SHELL_HISTORY_FILE \
	INCLUDE_SHELL_INTERP_C \
	INCLUDE_SHELL_INTERP_CMD \
	INCLUDE_SHELL_VI_MODE \
	INCLUDE_SHL \
	INCLUDE_SHL_SHELL_CMD \
	INCLUDE_SHL_SHOW \
	INCLUDE_SIGNALS \
	INCLUDE_SIGNAL_ARCH \
	INCLUDE_SIO \
	INCLUDE_SIO_UTILS \
	INCLUDE_SLL \
	INCLUDE_SOCKLIB \
	INCLUDE_SPINLOCK \
	INCLUDE_STANDALONE_SYM_TBL \
	INCLUDE_STDIO \
	INCLUDE_SYM_SHELL_CMD \
	INCLUDE_SYM_TBL \
	INCLUDE_SYM_TBL_INIT \
	INCLUDE_SYM_TBL_SHOW \
	INCLUDE_SYSCALL_HOOKS \
	INCLUDE_SYSCLK_INIT \
	INCLUDE_SYSCTL \
	INCLUDE_SYSCTL_HW \
	INCLUDE_SYSHW_INIT \
	INCLUDE_SYSHW_INIT2 \
	INCLUDE_SYS_START \
	INCLUDE_TASK_CREATE_DELETE \
	INCLUDE_TASK_CREATE_HOOKS \
	INCLUDE_TASK_HOOKS \
	INCLUDE_TASK_HOOKS_SHOW \
	INCLUDE_TASK_INFO \
	INCLUDE_TASK_LIST \
	INCLUDE_TASK_OPEN \
	INCLUDE_TASK_RESTART \
	INCLUDE_TASK_SHELL_CMD \
	INCLUDE_TASK_SHOW \
	INCLUDE_TASK_SWAP_HOOKS \
	INCLUDE_TASK_SWITCH_HOOKS \
	INCLUDE_TASK_UTIL \
	INCLUDE_TASK_VARS \
	INCLUDE_TELNET_CLIENT \
	INCLUDE_TIMER_SYS \
	INCLUDE_TIMER_SYS_DELAY \
	INCLUDE_TIMEX \
	INCLUDE_TIP \
	INCLUDE_TTY_DEV \
	INCLUDE_TYLIB \
	INCLUDE_UNLOADER \
	INCLUDE_UNLOADER_SHELL_CMD \
	INCLUDE_USER_APPL \
	INCLUDE_USE_NATIVE_SHELL \
	INCLUDE_VM_INVTBL \
	INCLUDE_VM_RTP \
	INCLUDE_VM_SHOW \
	INCLUDE_VM_SHOW_SHELL_CMD \
	INCLUDE_VXBUS \
	INCLUDE_VXBUS_ACTIVATE \
	INCLUDE_VXBUS_DEVICE_CONNECT \
	INCLUDE_VXBUS_DEV_INIT \
	INCLUDE_VXBUS_INIT \
	INCLUDE_VXB_SYS_CLK \
	INCLUDE_VXEVENTS \
	INCLUDE_VXMEMPROBE_INIT \
	INCLUDE_VXMUX_MBLK \
	INCLUDE_VXMUX_NULLBUFPOOL \
	INCLUDE_VX_TRADITIONAL_SCHEDULER \
	INCLUDE_WATCHDOGS \
	INCLUDE_WATCHDOGS_CREATE_DELETE \
	INCLUDE_WB_RUNTIME_SUPPORT \
	INCLUDE_WDB \
	INCLUDE_WDB_BANNER \
	INCLUDE_WDB_BP \
	INCLUDE_WDB_BP_SYNC \
	INCLUDE_WDB_COMM_END \
	INCLUDE_WDB_CTXT \
	INCLUDE_WDB_DIRECT_CALL \
	INCLUDE_WDB_EVENTPOINTS \
	INCLUDE_WDB_EVENTS \
	INCLUDE_WDB_EXC_NOTIFY \
	INCLUDE_WDB_EXIT_NOTIFY \
	INCLUDE_WDB_FUNC_CALL \
	INCLUDE_WDB_GOPHER \
	INCLUDE_WDB_KERNEL_INIT_DONE \
	INCLUDE_WDB_MDL_SYM_SYNC \
	INCLUDE_WDB_MEM \
	INCLUDE_WDB_POST_KERNEL_INIT \
	INCLUDE_WDB_REG \
	INCLUDE_WDB_RTP \
	INCLUDE_WDB_RTP_BP \
	INCLUDE_WDB_RTP_CONTROL \
	INCLUDE_WDB_START_NOTIFY \
	INCLUDE_WDB_SYS \
	INCLUDE_WDB_SYS_REG \
	INCLUDE_WDB_TASK \
	INCLUDE_WDB_TASK_BP \
	INCLUDE_WDB_TASK_HOOKS \
	INCLUDE_WDB_TASK_REG \
	INCLUDE_WDB_USER_EVENT \
	INCLUDE_WDB_VIO \
	INCLUDE_WDB_VIO_LIB \
	INCLUDE_XBD \
	INCLUDE_XBD_BLK_DEV \
	INCLUDE_XBD_PART_LIB \
	INIT_HWMEMPOOL_GLOBAL \
	VXBUS_TABLE_CONFIG

MANAGED_LIBS = libar521x.a libar521xVxbEnd.a libbcm43xx.a libbcm43xxVxbEnd.a libspl.a libtipc.a libvxdot1x.a libwlan.a libwlanVxbEnd.a
COMPONENT_LIBS = libspl.a

PROJECT_LINK_SYMDEFS = 


include $(TGT_DIR)/h/make/defs.project


## build-configuration info

ifeq ($(BUILD_SPEC),default)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(SUB_TARGETS) $(PRJ_DIR)/comDrv.o $(PRJ_DIR)/canDrv.o $(PRJ_DIR)/sjaDrv.o $(PRJ_DIR)/mspCom.o
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM/gnu -L$(VSB_DIR)/pentium/PENTIUM/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_rom)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM/gnu -L$(VSB_DIR)/pentium/PENTIUM/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_SIZE         = 00090000	# number of bytes of ROM space
ROM_TEXT_ADRS    = 00008000	# ROM entry address - A: or C:
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM/gnu -L$(VSB_DIR)/pentium/PENTIUM/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_SIZE         = 00090000	# number of bytes of ROM space
ROM_TEXT_ADRS    = 00008000	# ROM entry address - A: or C:
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
AR               = arpentium
AS               = ccpentium
BOOT_EXTRA       = 
CC               = ccpentium
CC_ARCH_SPEC     = -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop
CFLAGS           = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS        = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(PRJ_DIR) -I$(BSP_DIR) -I$(TGT_DIR)/h -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/drv -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -DPRJ_BUILD -D_WRS_KERNEL -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -I.
CFLAGS_AS_PROJECT = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CFLAGS_PROJECT   = -g -mtune=pentium -march=pentium -nostdlib -fno-builtin -fno-defer-pop -ansi -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.3/h -I$(WIND_HOME)/components/webservices-1.7/h -I$(WIND_HOME)/components/webcli-4.8/target/h -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.3/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.8/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=PENTIUM -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DFAST_REBOOT -DIP_PORT_VXWORKS=68 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\"
CPP              = ccpentium -E -P
EXTRA_MODULES    = $(BSP_DIR)/KEY/vxbI8042Kbd.o $(SUB_TARGETS)
HEX_FLAGS        = 
LD               = ldpentium
LD_LINK_PATH     = -L$(VSB_DIR)/pentium/PENTIUM/gnu_standard -L$(VSB_DIR)/pentium/PENTIUM/gnu -L$(VSB_DIR)/pentium/PENTIUM/common -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/gnu -L$(WIND_HOME)/components/obj/vxworks-6.8/krnl/lib/pentium/PENTIUM/common
LD_PARTIAL       = ccpentium -r -nostdlib -Wl,-X
LD_PARTIAL_FLAGS = -X -r
LIBS             = $(VX_OS_LIBS)
NM               = nmpentium -g
OPTION_DEFINE_MACRO = -D
OPTION_DEPEND    = -M -w
OPTION_GENERATE_DEPENDENCY_FILE = -MD
OPTION_INCLUDE_DIR = -I
OPTION_LANG_C    = -xc
OPTION_UNDEFINE_MACRO = -U
ROM_SIZE         = 00090000	# number of bytes of ROM space
ROM_TEXT_ADRS    = 00008000	# ROM entry address - A: or C:
SIZE             = sizepentium
TOOL_FAMILY      = gnu
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

# override make definitions only below this line


# override make definitions only above this line

include $(TGT_DIR)/h/make/rules.project


## build-configuration info

sysALib.o: $(PRJ_DIR)/prjParams.h

ifeq ($(BUILD_SPEC),default)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

CtrlAlgorithm.o:  $(PRJ_DIR)/CtrlAlgorithm.c 
	$(RM) CtrlAlgorithm.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/CtrlAlgorithm.c

DataProcess.o:  $(PRJ_DIR)/DataProcess.c 
	$(RM) DataProcess.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/DataProcess.c

PowerManage.o:  $(PRJ_DIR)/PowerManage.c 
	$(RM) PowerManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PowerManage.c

SailingBox.o:  $(PRJ_DIR)/SailingBox.c 
	$(RM) SailingBox.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SailingBox.c

sax.o:  $(PRJ_DIR)/XML/sax.c 
	$(RM) sax.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/sax.c

xmlparse.o:  $(PRJ_DIR)/XML/xmlparse.c 
	$(RM) xmlparse.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlparse.c

xmlrole.o:  $(PRJ_DIR)/XML/xmlrole.c 
	$(RM) xmlrole.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlrole.c

xmltok.o:  $(PRJ_DIR)/XML/xmltok.c 
	$(RM) xmltok.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok.c

xmltok_impl.o:  $(PRJ_DIR)/XML/xmltok_impl.c 
	$(RM) xmltok_impl.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_impl.c

xmltok_ns.o:  $(PRJ_DIR)/XML/xmltok_ns.c 
	$(RM) xmltok_ns.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_ns.c

xpp.o:  $(PRJ_DIR)/XML/xpp.c 
	$(RM) xpp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xpp.c

xppTutorialAll.o:  $(PRJ_DIR)/XML/xppTutorialAll.c 
	$(RM) xppTutorialAll.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xppTutorialAll.c

XMLFile.o:  $(PRJ_DIR)/XMLFile.c 
	$(RM) XMLFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XMLFile.c

com.o:  $(PRJ_DIR)/com.c 
	$(RM) com.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/com.c

dtp.o:  $(PRJ_DIR)/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/dtp.c

main.o:  $(PRJ_DIR)/main.c 
	$(RM) main.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/main.c

canTest.o:  $(PRJ_DIR)/canTest.c 
	$(RM) canTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/canTest.c

SecurityEmergencyManage.o:  $(PRJ_DIR)/SecurityEmergencyManage.c 
	$(RM) SecurityEmergencyManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SecurityEmergencyManage.c
endif

ifeq ($(BUILD_SPEC),default_rom)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

CtrlAlgorithm.o:  $(PRJ_DIR)/CtrlAlgorithm.c 
	$(RM) CtrlAlgorithm.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/CtrlAlgorithm.c

DataProcess.o:  $(PRJ_DIR)/DataProcess.c 
	$(RM) DataProcess.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/DataProcess.c

PowerManage.o:  $(PRJ_DIR)/PowerManage.c 
	$(RM) PowerManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PowerManage.c

SailingBox.o:  $(PRJ_DIR)/SailingBox.c 
	$(RM) SailingBox.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SailingBox.c

sax.o:  $(PRJ_DIR)/XML/sax.c 
	$(RM) sax.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/sax.c

xmlparse.o:  $(PRJ_DIR)/XML/xmlparse.c 
	$(RM) xmlparse.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlparse.c

xmlrole.o:  $(PRJ_DIR)/XML/xmlrole.c 
	$(RM) xmlrole.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlrole.c

xmltok.o:  $(PRJ_DIR)/XML/xmltok.c 
	$(RM) xmltok.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok.c

xmltok_impl.o:  $(PRJ_DIR)/XML/xmltok_impl.c 
	$(RM) xmltok_impl.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_impl.c

xmltok_ns.o:  $(PRJ_DIR)/XML/xmltok_ns.c 
	$(RM) xmltok_ns.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_ns.c

xpp.o:  $(PRJ_DIR)/XML/xpp.c 
	$(RM) xpp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xpp.c

xppTutorialAll.o:  $(PRJ_DIR)/XML/xppTutorialAll.c 
	$(RM) xppTutorialAll.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xppTutorialAll.c

XMLFile.o:  $(PRJ_DIR)/XMLFile.c 
	$(RM) XMLFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XMLFile.c

com.o:  $(PRJ_DIR)/com.c 
	$(RM) com.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/com.c

dtp.o:  $(PRJ_DIR)/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/dtp.c

main.o:  $(PRJ_DIR)/main.c 
	$(RM) main.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/main.c

canTest.o:  $(PRJ_DIR)/canTest.c 
	$(RM) canTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/canTest.c

SecurityEmergencyManage.o:  $(PRJ_DIR)/SecurityEmergencyManage.c 
	$(RM) SecurityEmergencyManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SecurityEmergencyManage.c
endif

ifeq ($(BUILD_SPEC),default_romCompress)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

CtrlAlgorithm.o:  $(PRJ_DIR)/CtrlAlgorithm.c 
	$(RM) CtrlAlgorithm.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/CtrlAlgorithm.c

DataProcess.o:  $(PRJ_DIR)/DataProcess.c 
	$(RM) DataProcess.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/DataProcess.c

PowerManage.o:  $(PRJ_DIR)/PowerManage.c 
	$(RM) PowerManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PowerManage.c

SailingBox.o:  $(PRJ_DIR)/SailingBox.c 
	$(RM) SailingBox.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SailingBox.c

sax.o:  $(PRJ_DIR)/XML/sax.c 
	$(RM) sax.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/sax.c

xmlparse.o:  $(PRJ_DIR)/XML/xmlparse.c 
	$(RM) xmlparse.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlparse.c

xmlrole.o:  $(PRJ_DIR)/XML/xmlrole.c 
	$(RM) xmlrole.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlrole.c

xmltok.o:  $(PRJ_DIR)/XML/xmltok.c 
	$(RM) xmltok.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok.c

xmltok_impl.o:  $(PRJ_DIR)/XML/xmltok_impl.c 
	$(RM) xmltok_impl.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_impl.c

xmltok_ns.o:  $(PRJ_DIR)/XML/xmltok_ns.c 
	$(RM) xmltok_ns.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_ns.c

xpp.o:  $(PRJ_DIR)/XML/xpp.c 
	$(RM) xpp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xpp.c

xppTutorialAll.o:  $(PRJ_DIR)/XML/xppTutorialAll.c 
	$(RM) xppTutorialAll.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xppTutorialAll.c

XMLFile.o:  $(PRJ_DIR)/XMLFile.c 
	$(RM) XMLFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XMLFile.c

com.o:  $(PRJ_DIR)/com.c 
	$(RM) com.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/com.c

dtp.o:  $(PRJ_DIR)/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/dtp.c

main.o:  $(PRJ_DIR)/main.c 
	$(RM) main.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/main.c

canTest.o:  $(PRJ_DIR)/canTest.c 
	$(RM) canTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/canTest.c

SecurityEmergencyManage.o:  $(PRJ_DIR)/SecurityEmergencyManage.c 
	$(RM) SecurityEmergencyManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SecurityEmergencyManage.c
endif

ifeq ($(BUILD_SPEC),default_romResident)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c

CtrlAlgorithm.o:  $(PRJ_DIR)/CtrlAlgorithm.c 
	$(RM) CtrlAlgorithm.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/CtrlAlgorithm.c

DataProcess.o:  $(PRJ_DIR)/DataProcess.c 
	$(RM) DataProcess.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/DataProcess.c

PowerManage.o:  $(PRJ_DIR)/PowerManage.c 
	$(RM) PowerManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/PowerManage.c

SailingBox.o:  $(PRJ_DIR)/SailingBox.c 
	$(RM) SailingBox.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SailingBox.c

sax.o:  $(PRJ_DIR)/XML/sax.c 
	$(RM) sax.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/sax.c

xmlparse.o:  $(PRJ_DIR)/XML/xmlparse.c 
	$(RM) xmlparse.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlparse.c

xmlrole.o:  $(PRJ_DIR)/XML/xmlrole.c 
	$(RM) xmlrole.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmlrole.c

xmltok.o:  $(PRJ_DIR)/XML/xmltok.c 
	$(RM) xmltok.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok.c

xmltok_impl.o:  $(PRJ_DIR)/XML/xmltok_impl.c 
	$(RM) xmltok_impl.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_impl.c

xmltok_ns.o:  $(PRJ_DIR)/XML/xmltok_ns.c 
	$(RM) xmltok_ns.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xmltok_ns.c

xpp.o:  $(PRJ_DIR)/XML/xpp.c 
	$(RM) xpp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xpp.c

xppTutorialAll.o:  $(PRJ_DIR)/XML/xppTutorialAll.c 
	$(RM) xppTutorialAll.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XML/xppTutorialAll.c

XMLFile.o:  $(PRJ_DIR)/XMLFile.c 
	$(RM) XMLFile.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/XMLFile.c

com.o:  $(PRJ_DIR)/com.c 
	$(RM) com.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/com.c

dtp.o:  $(PRJ_DIR)/dtp.c 
	$(RM) dtp.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/dtp.c

main.o:  $(PRJ_DIR)/main.c 
	$(RM) main.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/main.c

canTest.o:  $(PRJ_DIR)/canTest.c 
	$(RM) canTest.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/canTest.c

SecurityEmergencyManage.o:  $(PRJ_DIR)/SecurityEmergencyManage.c 
	$(RM) SecurityEmergencyManage.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/SecurityEmergencyManage.c
endif


## user defined rules

romStart.o : $(TGT_DIR)/config/comps/src/romStart.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

romcard_bootrom_512.hex: depend.$(BSP_NAME) romcard.o bootrom_uncmp
	- @ $(RM) $@
	$(LD) -o romcard -X -N -e _romcard romcard.o
	$(ROMSIZEPROG) -b 7fe00 bootrom_uncmp
	$(BINHEX) -a 0 bootrom_uncmp | $(SED) -e "/S9/d" > $@
	$(BINHEX) -a 7fe00 -b romcard >> $@
	- @ $(RM) romcard.o romcard
	$(POST_HEX_BUILD_RULE)

#   bootrom		- bootrom(compressed):		   upper mem

romInit.o : $(TGT_DIR)/config/BSP/romInit.s
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(ROM_FLAGS_EXTRA) $< -o $@

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/linkSyms.c -o $@

#   bootrom_uncmp	- bootrom:			   upper mem

romcard_bootrom_256.hex: depend.$(BSP_NAME) romcard.o bootrom_uncmp
	- @ $(RM) $@
	$(LD) -o romcard -X -N -e _romcard romcard.o
	$(ROMSIZEPROG) -b 3fe00 bootrom_uncmp
	$(BINHEX) -a 0 bootrom_uncmp | $(SED) -e "/S9/d" > $@
	$(BINHEX) -a 3fe00 -b romcard >> $@
	- @ $(RM) romcard.o romcard
	$(POST_HEX_BUILD_RULE)

sysLib.o : $(TGT_DIR)/config/BSP/sysLib.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(TGT_DIR)/config/BSP/sysLib.c -o $@

romcard_vxWorks_st_512.hex: depend.$(BSP_NAME) romcard.o vxWorks.st_rom
	- @ $(RM) $@
	$(LD) -o romcard -X -N -e _romcard romcard.o
	$(ROMSIZEPROG) -b 7fe00 vxWorks.st_rom
	$(BINHEX) -a 0 vxWorks.st_rom | $(SED) -e "/S9/d" > $@
	$(BINHEX) -a 7fe00 -b romcard >> $@
	- @ $(RM) romcard.o romcard
	$(POST_HEX_BUILD_RULE)

sysALib.o : $(TGT_DIR)/config/BSP/sysALib.s
	$(AS) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(TGT_DIR)/config/BSP/sysALib.s -o $@

bootrom.pxe: bootrom.bin pxeBoot.bin
	cat pxeBoot.bin bootrom.bin > bootrom.pxe

#   vxWorks.st_rom	- bootable vxWorks.st(compressed): upper mem

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/prjConfig.c -o $@


src_build :

src_depend :

$(PRJ_FULL_PATH)/compObjs.lst : $(PRJ_MAKEFILE)
	@ $(RM) $@
	@ touch $@

src_clean :
	@ $(RM) compObjs.lst
